/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sabe.apresentacao;

import br.com.sabe.entidade.Beneficiario;
import br.com.sabe.entidade.PedidoAveriguacao;
import br.com.sabe.excecao.CampoObrigatorioException;
import br.com.sabe.excecao.PedidoAveriguacaoExistenteException;
import br.com.sabe.excecao.SistemaAveriguacaoException;
import br.com.sabe.negocio.BeneficiarioBO;
import br.com.sabe.negocio.PedidoAveriguacaoBO;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author walisson
 */
public class CadastroPedidoAveriguacaoForm extends javax.swing.JFrame {
    Beneficiario beneficiario;
    PedidoAveriguacao pedidoAveriguacao;
    ConsultaPedidoAveriguacaoForm consultaPedido;
    int acaoTela=0;
    /**
     * Creates new form CadastroPedidoAveriguacao
     */
    public CadastroPedidoAveriguacaoForm() {
        this.acaoTela = 0;
        this.prepararTela();
        this.pedidoAveriguacao = new PedidoAveriguacao();
    }
    public CadastroPedidoAveriguacaoForm(Beneficiario beneficiarioCadastrado){
        this.acaoTela = 1;
        this.beneficiario = beneficiarioCadastrado;
        this.prepararTela();
    }
    public CadastroPedidoAveriguacaoForm(PedidoAveriguacao pedidoAveriguacaoConsultado,
            ConsultaPedidoAveriguacaoForm consultaPedidoAveriguacaoForm){
        this.acaoTela = 2;
        this.pedidoAveriguacao = pedidoAveriguacaoConsultado;
        this.consultaPedido = consultaPedidoAveriguacaoForm;
        this.beneficiario = pedidoAveriguacaoConsultado.getBeneficiario();
        this.prepararTela();
    }
    public void prepararTela(){
        try {
            this.initComponents();
            if(acaoTela != 0){
                this.inicializarCamposTela();
            }    
        } catch (Exception e) {
            String mensagem = "Erro inesperado! Informe a mensagem de erro ao administrador do sistema.";
            mensagem += "\nMensagem de erro:\n" + e.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Pedido de Averiguacao", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }
    private void inicializarCamposTela() {
        this.lblNomeTitularAtivo.setText(beneficiario.getNome());
        this.txtNisTitular.setText(beneficiario.getNis());
        this.lblNomeTitularAtivo.setEnabled(false);
        this.txtNisTitular.setEnabled(false);
        if(this.acaoTela == 2){
            SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");        
            this.txtDataPedido.setText(formatador.format(this.pedidoAveriguacao.getDataPedido()));
            this.txtSituacao.setText(pedidoAveriguacao.getSituacao());
        }
    }
    private void validarCamposObrigatorios(){
        if(this.txtDataPedido.getText().trim().equals("") ||
                this.txtSituacao.getText().trim().equals("") ||
                this.txtNisTitular.getText().trim().equals("") ||
                this.lblNomeTitularAtivo.getText().trim().equals("")){
            throw new CampoObrigatorioException();
        }
    }
    private void limparCamposTela(){
        txtDataPedido.setText("");
        txtSituacao.setText("");
        txtNisTitular.setText("");
        lblNomeTitularAtivo.setText("");
    }
    public void recuperarCamposTela() throws ParseException{
        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
        Date data = formatador.parse(txtDataPedido.getText().trim());
        this.pedidoAveriguacao.setDataPedido(data);
        this.pedidoAveriguacao.setSituacao(this.txtSituacao.getText());
        this.pedidoAveriguacao.setBeneficiario(this.beneficiario);
    }
    private String lerNisTitular() {
        String nis = txtNisTitular.getText().trim();

        String mensagem = "";

        if (nis.length() < 11) {
            mensagem = "NIS inválido";
        }

        if (!(mensagem == "" || mensagem == null)) {
            throw new CampoObrigatorioException(mensagem);
        }

        return nis;
    }
    private void setNomeBeneficiarioTela() {
        lblNomeTitualar.setVisible(true);
        lblNomeTitularAtivo.setText(beneficiario.getNome());
        lblNomeTitularAtivo.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeTitualar = new javax.swing.JPanel();
        lblCamposObrigatorios = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        pnlBeneficiario = new javax.swing.JPanel();
        VerificarNis = new javax.swing.JButton();
        txtNisTitular = new javax.swing.JFormattedTextField();
        lblNomeTitular = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        lblNomeTitularAtivo = new javax.swing.JLabel();
        pnlMotivoAveriguacao = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSituacao = new javax.swing.JTextArea();
        lblDescricao = new javax.swing.JLabel();
        lblDataPedido = new javax.swing.JLabel();
        txtDataPedido = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Cadastro de Pedido de Averiguação");
        setExtendedState(6);

        lblNomeTitualar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pedidos de Averiguacao", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        lblNomeTitualar.setToolTipText("TelaUsuarios");
        lblNomeTitualar.setAutoscrolls(true);

        lblCamposObrigatorios.setForeground(new java.awt.Color(230, 45, 12));
        lblCamposObrigatorios.setText("* Campos Obrigatórios");

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabe/apresentacao/icones/1467304636_search.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setAlignmentX(0.5F);
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabe/apresentacao/icones/cross79.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.setAlignmentX(0.5F);
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabe/apresentacao/icones/text133_1.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setAlignmentX(0.5F);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabe/apresentacao/icones/save (2).png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setAlignmentX(0.5F);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        pnlBeneficiario.setBorder(javax.swing.BorderFactory.createTitledBorder("Beneficiário"));

        VerificarNis.setText("Verificar");
        VerificarNis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerificarNisActionPerformed(evt);
            }
        });

        lblNomeTitular.setText("*Nome do Titular:");

        lblLogin.setText("*NIS do Beneficiario Titular:");

        lblNomeTitularAtivo.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        javax.swing.GroupLayout pnlBeneficiarioLayout = new javax.swing.GroupLayout(pnlBeneficiario);
        pnlBeneficiario.setLayout(pnlBeneficiarioLayout);
        pnlBeneficiarioLayout.setHorizontalGroup(
            pnlBeneficiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBeneficiarioLayout.createSequentialGroup()
                .addGroup(pnlBeneficiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogin)
                    .addComponent(lblNomeTitular))
                .addGap(1, 1, 1)
                .addGroup(pnlBeneficiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBeneficiarioLayout.createSequentialGroup()
                        .addComponent(txtNisTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VerificarNis, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlBeneficiarioLayout.createSequentialGroup()
                        .addComponent(lblNomeTitularAtivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        pnlBeneficiarioLayout.setVerticalGroup(
            pnlBeneficiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBeneficiarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBeneficiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogin)
                    .addComponent(VerificarNis)
                    .addComponent(txtNisTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBeneficiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeTitular)
                    .addComponent(lblNomeTitularAtivo, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlMotivoAveriguacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Motivo da Averiguação"));

        txtSituacao.setColumns(20);
        txtSituacao.setRows(5);
        jScrollPane1.setViewportView(txtSituacao);

        lblDescricao.setText("Situação:");

        lblDataPedido.setText("Data do Pedido:");

        txtDataPedido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        txtDataPedido.setToolTipText("");

        javax.swing.GroupLayout pnlMotivoAveriguacaoLayout = new javax.swing.GroupLayout(pnlMotivoAveriguacao);
        pnlMotivoAveriguacao.setLayout(pnlMotivoAveriguacaoLayout);
        pnlMotivoAveriguacaoLayout.setHorizontalGroup(
            pnlMotivoAveriguacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMotivoAveriguacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMotivoAveriguacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataPedido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMotivoAveriguacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlMotivoAveriguacaoLayout.createSequentialGroup()
                        .addComponent(txtDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlMotivoAveriguacaoLayout.setVerticalGroup(
            pnlMotivoAveriguacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMotivoAveriguacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMotivoAveriguacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDataPedido)
                    .addComponent(txtDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlMotivoAveriguacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMotivoAveriguacaoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDescricao)
                        .addGap(44, 44, 44))
                    .addGroup(pnlMotivoAveriguacaoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout lblNomeTitualarLayout = new javax.swing.GroupLayout(lblNomeTitualar);
        lblNomeTitualar.setLayout(lblNomeTitualarLayout);
        lblNomeTitualarLayout.setHorizontalGroup(
            lblNomeTitualarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblNomeTitualarLayout.createSequentialGroup()
                .addGroup(lblNomeTitualarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMotivoAveriguacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBeneficiario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(lblNomeTitualarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lblNomeTitualarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblNomeTitualarLayout.createSequentialGroup()
                        .addComponent(lblCamposObrigatorios)
                        .addGap(588, 588, 588))
                    .addGroup(lblNomeTitualarLayout.createSequentialGroup()
                        .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 291, Short.MAX_VALUE)
                        .addComponent(btnPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        lblNomeTitualarLayout.setVerticalGroup(
            lblNomeTitualarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblNomeTitualarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBeneficiario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlMotivoAveriguacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(193, 193, 193)
                .addComponent(lblCamposObrigatorios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(lblNomeTitualarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNomeTitualar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNomeTitualar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        String mensagem = "Os dados ja preenchidos serao descartados";
        String titulo = "Pesquisar Pedidos de Averiguações Cadastrados";
        int resposta = JOptionPane.showConfirmDialog(null, mensagem, titulo, JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {
            limparCamposTela();
            if(this.consultaPedido == null){
                consultaPedido = new ConsultaPedidoAveriguacaoForm();
            }
            consultaPedido.setVisible(true);
            this.dispose();
        }         
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        String mensagem = "Deseja fechar a tela de pedido de Averigacao?"
                + "Os dados ja preenchidos serao descartados!";
        String titulo = "Fechar Tela Cadastro de Pedidos de Averiguacao";
        int resposta = JOptionPane.showConfirmDialog(null, mensagem, titulo, JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {
            limparCamposTela();
            this.dispose();
        }  
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        int resposta;
        String mensagem = "Os dados ja preenchidos serao descartados";
        String titulo = "Cadastrar Novo";
        resposta = JOptionPane.showConfirmDialog(null, mensagem, titulo, JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {
            limparCamposTela();
        }
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            PedidoAveriguacaoBO pedidoAveriguacaoBO = new PedidoAveriguacaoBO();
            this.validarCamposObrigatorios();
            this.recuperarCamposTela();
            if(this.acaoTela == 0){
                pedidoAveriguacaoBO.inserir(this.pedidoAveriguacao);
                JOptionPane.showMessageDialog(this, "Pedido de averiguação cadastrado com sucesso!", 
                        "Cadastro de Pedido de Averiguacao", JOptionPane.INFORMATION_MESSAGE);
            }else{    
                pedidoAveriguacaoBO.atualizar(this.pedidoAveriguacao);           
                JOptionPane.showMessageDialog(this, "Pedido de averiguação atualizado com sucesso!", 
                        "Atualizar Pedido de Averiguacao", JOptionPane.INFORMATION_MESSAGE);
                this.consultaPedido.carregarTabelaPedidoAveriguacao();
            } 
            this.limparCamposTela();
            
        }catch(SistemaAveriguacaoException sae){
            String mensagem = "Erro ao realizar operação:\n" + sae.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Cadastro de aluno", JOptionPane.ERROR_MESSAGE);
        }catch(Exception e){
            String mensagem = "Erro inesperado! Informe a mensagem de erro ao administrador do sistema.";
            mensagem += "\nMensagem de erro:\n" + e.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Cadastro de usuario", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void VerificarNisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerificarNisActionPerformed
        try {
            BeneficiarioBO beneficiarioBO= new BeneficiarioBO();
            beneficiario = beneficiarioBO.buscarByNis(lerNisTitular());
            PedidoAveriguacaoBO pedidoAveriguacaoBO = new PedidoAveriguacaoBO();
            pedidoAveriguacaoBO.verificarPedidoAveriguacaoExistente(lerNisTitular());
            this.setNomeBeneficiarioTela();
        } catch (SistemaAveriguacaoException se) {
            JOptionPane.showMessageDialog(this, se.getMessage(), "Consultar Beneficiario", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Não foi possivel consultar o beneficiário \nTente novamente", "Cadastro pedido de Averiguacao", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_VerificarNisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPedidoAveriguacaoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPedidoAveriguacaoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPedidoAveriguacaoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPedidoAveriguacaoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPedidoAveriguacaoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VerificarNis;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCamposObrigatorios;
    private javax.swing.JLabel lblDataPedido;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JPanel lblNomeTitualar;
    private javax.swing.JLabel lblNomeTitular;
    private javax.swing.JLabel lblNomeTitularAtivo;
    private javax.swing.JPanel pnlBeneficiario;
    private javax.swing.JPanel pnlMotivoAveriguacao;
    private javax.swing.JFormattedTextField txtDataPedido;
    private javax.swing.JFormattedTextField txtNisTitular;
    private javax.swing.JTextArea txtSituacao;
    // End of variables declaration//GEN-END:variables

    
}
