/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sabe.apresentacao;

import br.com.sabe.entidade.Beneficio;
import br.com.sabe.excecao.CampoObrigatorioException;
import br.com.sabe.excecao.SistemaAveriguacaoException;
import br.com.sabe.negocio.BeneficioBO;
import br.com.sabe.negocio.UsuarioBO;
import java.text.DecimalFormat;
import java.text.ParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author walisson
 */
public class CadastroBeneficioForm extends javax.swing.JFrame {
    Beneficio beneficio = null;
    int acao = 0;
    /**
     * Creates new form CadastroBeneficioForm
     */
    public CadastroBeneficioForm() {
        beneficio = new Beneficio();
        initComponents();       
    }
    public CadastroBeneficioForm(Beneficio beneficioConsultado){
        this.beneficio = beneficioConsultado;
        initComponents();
        inicializarCamposTela();
        this.acao = 1;
    }
    public void limparCamposTela(){
        txtNomeBeneficio.setText("");
        txtTipoBeneficio.setText("");
        txtValorBeneficio.setText("");
    }
    public void recuperarCamposTela() throws ParseException{
        beneficio.setNome(txtNomeBeneficio.getText());
        beneficio.setTipo(txtTipoBeneficio.getText());
        String strValor = txtValorBeneficio.getText();
        DecimalFormat formatador = new DecimalFormat("#,##0.00");
        Double valor = formatador.parse(strValor).doubleValue();
        beneficio.setValor(valor);
    }
    public void inicializarCamposTela(){
        this.txtNomeBeneficio.setText(this.beneficio.getNome());
        this.txtTipoBeneficio.setText(this.beneficio.getTipo());
        
        DecimalFormat formatador = new DecimalFormat("#,##0.00");
        this.txtValorBeneficio.setText(formatador.format(this.beneficio.getValor()));
    }
    
    public void validarCamposObrigatorios(){
        if(txtNomeBeneficio.getText().trim().isEmpty()||
        txtTipoBeneficio.getText().trim().isEmpty()||
        txtValorBeneficio.getText().trim().isEmpty()){
            throw new CampoObrigatorioException();
        }        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCadastroBeneficiario = new javax.swing.JPanel();
        lblCamposObrigatorios = new javax.swing.JLabel();
        txtNomeBeneficio = new javax.swing.JTextField();
        lblTipoBeneficio = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        lblNomeBeneficio = new javax.swing.JLabel();
        lblValorBeneficio = new javax.swing.JLabel();
        txtTipoBeneficio = new javax.swing.JTextField();
        btnFechar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        txtValorBeneficio = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Beneficio");
        setExtendedState(6);

        pnlCadastroBeneficiario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Benefício", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        pnlCadastroBeneficiario.setToolTipText("Tela Cadastro de Beneficio");
        pnlCadastroBeneficiario.setAutoscrolls(true);

        lblCamposObrigatorios.setForeground(new java.awt.Color(230, 45, 12));
        lblCamposObrigatorios.setText("* Campos Obrigatórios");

        txtNomeBeneficio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeBeneficioFocusLost(evt);
            }
        });
        txtNomeBeneficio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeBeneficioActionPerformed(evt);
            }
        });

        lblTipoBeneficio.setText("Tipo de Beneficio:");

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabe/apresentacao/icones/1467304636_search.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setAlignmentX(0.5F);
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        lblNomeBeneficio.setText("Nome do Beneficio:");

        lblValorBeneficio.setText("Valor do Benefício:");

        txtTipoBeneficio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTipoBeneficioFocusLost(evt);
            }
        });
        txtTipoBeneficio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoBeneficioActionPerformed(evt);
            }
        });

        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabe/apresentacao/icones/cross79.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.setAlignmentX(0.5F);
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabe/apresentacao/icones/text133_1.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setAlignmentX(0.5F);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabe/apresentacao/icones/save (2).png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setAlignmentX(0.5F);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        txtValorBeneficio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        javax.swing.GroupLayout pnlCadastroBeneficiarioLayout = new javax.swing.GroupLayout(pnlCadastroBeneficiario);
        pnlCadastroBeneficiario.setLayout(pnlCadastroBeneficiarioLayout);
        pnlCadastroBeneficiarioLayout.setHorizontalGroup(
            pnlCadastroBeneficiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroBeneficiarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCadastroBeneficiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadastroBeneficiarioLayout.createSequentialGroup()
                        .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, Short.MAX_VALUE)
                        .addComponent(btnPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(pnlCadastroBeneficiarioLayout.createSequentialGroup()
                        .addGroup(pnlCadastroBeneficiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomeBeneficio)
                            .addComponent(lblTipoBeneficio))
                        .addGap(1, 1, 1)
                        .addGroup(pnlCadastroBeneficiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTipoBeneficio)
                            .addComponent(txtNomeBeneficio)))
                    .addGroup(pnlCadastroBeneficiarioLayout.createSequentialGroup()
                        .addComponent(lblCamposObrigatorios)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlCadastroBeneficiarioLayout.createSequentialGroup()
                        .addComponent(lblValorBeneficio)
                        .addGap(7, 7, 7)
                        .addComponent(txtValorBeneficio))))
        );
        pnlCadastroBeneficiarioLayout.setVerticalGroup(
            pnlCadastroBeneficiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadastroBeneficiarioLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(pnlCadastroBeneficiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeBeneficio)
                    .addComponent(txtNomeBeneficio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCadastroBeneficiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoBeneficio)
                    .addComponent(txtTipoBeneficio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCadastroBeneficiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorBeneficio)
                    .addComponent(txtValorBeneficio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(263, 263, 263)
                .addComponent(lblCamposObrigatorios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCadastroBeneficiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCadastroBeneficiario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCadastroBeneficiario, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeBeneficioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeBeneficioFocusLost
        
    }//GEN-LAST:event_txtNomeBeneficioFocusLost

    private void txtNomeBeneficioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeBeneficioActionPerformed
        
    }//GEN-LAST:event_txtNomeBeneficioActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
       
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtTipoBeneficioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTipoBeneficioFocusLost
        
    }//GEN-LAST:event_txtTipoBeneficioFocusLost

    private void txtTipoBeneficioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoBeneficioActionPerformed

    }//GEN-LAST:event_txtTipoBeneficioActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        int resposta;
        String mensagem = "Os dados ja preenchidos serao descartados";
        String titulo = "Cadastrar Novo";
        resposta = JOptionPane.showConfirmDialog(null, mensagem, titulo, JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {
            this.limparCamposTela();
            txtNomeBeneficio.setEnabled(true);
        }
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            BeneficioBO beneficioBO = new BeneficioBO();
            this.validarCamposObrigatorios();
            this.recuperarCamposTela();
            if(acao != 0){
                beneficioBO.alterar(beneficio);       
                JOptionPane.showMessageDialog(this, "Beneficio alterado com sucesso!",
                "Editar Beneficio", JOptionPane.INFORMATION_MESSAGE);
            }
            beneficioBO.inserir(beneficio);       
            JOptionPane.showMessageDialog(this, "Beneficio cadastrado com sucesso!",
                "Cadastro Beneficio", JOptionPane.INFORMATION_MESSAGE);
            this.limparCamposTela();
            //desabilitarBotoesTela();
        }catch(SistemaAveriguacaoException sae){
            String mensagem = "Erro ao realizar operação:\n" + sae.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Cadastro de benefcio", JOptionPane.ERROR_MESSAGE);
        }catch(Exception e){
            String mensagem = "Erro inesperado! Informe a mensagem de erro ao administrador do sistema.";
            mensagem += "\nMensagem de erro:\n" + e.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Cadastro de benefico", JOptionPane.ERROR_MESSAGE);
        }   
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroBeneficioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroBeneficioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroBeneficioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroBeneficioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroBeneficioForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblCamposObrigatorios;
    private javax.swing.JLabel lblNomeBeneficio;
    private javax.swing.JLabel lblTipoBeneficio;
    private javax.swing.JLabel lblValorBeneficio;
    private javax.swing.JPanel pnlCadastroBeneficiario;
    private javax.swing.JTextField txtNomeBeneficio;
    private javax.swing.JTextField txtTipoBeneficio;
    private javax.swing.JFormattedTextField txtValorBeneficio;
    // End of variables declaration//GEN-END:variables
}
