/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sabe.apresentacao;

import br.com.sabe.apresentacao.classesUteis.DocumentoLimitado;
import br.com.sabe.apresentacao.classesUteis.Criptografia;
import br.com.sabe.entidade.Usuario;
import br.com.sabe.excecao.ArgumentoInvalidoException;
import br.com.sabe.excecao.CampoObrigatorioException;
import br.com.sabe.excecao.SistemaAveriguacaoException;
import br.com.sabe.negocio.UsuarioBO;
import java.io.UnsupportedEncodingException;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author wff
 */
public class TelaPrincipalForm extends javax.swing.JFrame {
    String senha;
    String login;
    Usuario usuario;
    TelaRelatorios telaRelatorios = null;
    CadastroUsuarioForm cadastroUsuario = null;
    ConsultarUsuarioForm consultaUsuario = null;
    CadastroBeneficioForm cadastroBeneficio = null;
    CadastroBeneficiarioForm cadastroBeneficiario = null;
    CadastroPedidoAveriguacaoForm cadastroPedidoAveriguacao = null;
    CadastroResultadoAveriguacaoForm cadastroResultadoAveriguacao = null;
    ConsultaBeneficiarioForm consultaBeneficiario = null;
    ConsultaBeneficioForm consultaBeneficio = null;
    ConsultaPedidoAveriguacaoForm consultaPedidoAveriguacao = null;
    ConsultaResultadoAveriguacaoForm consultaResultadoAveriguacao = null;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipalForm() {
        initComponents();
        //JInternalFrame1.pack();
        //JInternalFrame1.setSize(540, 540);
        this.mostrarComponentsSemUsuario();
        this.limitarCamposTela();
    }
    public void limitarCamposTela(){
        this.txtLogin.setDocument(new DocumentoLimitado(10));
        this.txtSenha.setDocument(new DocumentoLimitado(10));
        this.txtConfirmaSenha.setDocument(new DocumentoLimitado(10));
        
    }
    private void carregarUsuarioPermissao(){
        if(usuario.getCargo().equals("G")){
            mnuUsuarios.setVisible(true);
            mnuBeneficios.setVisible(true);
            mnuBeneficiarios.setVisible(true);
            mnuPedidoAveriguacao.setVisible(true);
            mnuResultadoAveriguacao.setVisible(true);
        }else if(usuario.getCargo().equals("AS")){
            mnuUsuarios.setVisible(false);
            mnuBeneficios.setVisible(false);
            mnuBeneficiarios.setVisible(true);
            mnuPedidoAveriguacao.setVisible(true);
            mnuResultadoAveriguacao.setVisible(true);
        
        }else if(usuario.getCargo().equals("OS")){
            mnuUsuarios.setVisible(false);
            mnuBeneficios.setVisible(false);
            mnuBeneficiarios.setVisible(true);
            mnuPedidoAveriguacao.setVisible(true);
            mnuResultadoAveriguacao.setVisible(false);
        
        }else if(usuario.getCargo().equals("R")){
            mnuUsuarios.setVisible(false);
            mnuBeneficios.setVisible(false);
            mnuBeneficiarios.setVisible(false);
            mnuPedidoAveriguacao.setVisible(false);
            mnuResultadoAveriguacao.setVisible(false);
        }
    }
    public void mostrarComponentsComUsuario(){
        this.setExtendedState(6);
        txtLogin.setEnabled(false);
        txtSenha.setEnabled(false);
        lblConfirmarSenha.setEnabled(false);
        txtConfirmaSenha.setEnabled(false);
        btnLogoff.setEnabled(true);
        btnLogin.setEnabled(false);
        btnAlterarSenha.setEnabled(true);
        btnConfirmarSenha.setEnabled(false);
        mnuBarMenuPrincipal.setVisible(true);
    }
    public void mostrarComponentsSemUsuario(){
        this.setExtendedState(0);
        txtLogin.setEnabled(true);
        txtSenha.setEnabled(true);
        lblConfirmarSenha.setEnabled(false);
        txtConfirmaSenha.setEnabled(false);
        btnLogoff.setEnabled(false);
        btnLogin.setEnabled(true);
        btnAlterarSenha.setEnabled(false);
        btnConfirmarSenha.setEnabled(false);
        mnuBarMenuPrincipal.setVisible(false);
        //jInternalFrame1.setSize(555, 460);
        
    }
    public void mostrarComponentesAlterarSenha(){
        txtLogin.setEnabled(false);
        lblSenha.setEnabled(true);
        txtSenha.setEnabled(true);
        txtSenha.setText("");
        lblConfirmarSenha.setEnabled(true);
        txtConfirmaSenha.setEnabled(true);
        btnLogoff.setEnabled(false);
        btnLogin.setEnabled(false);
        btnAlterarSenha.setEnabled(false);
        btnConfirmarSenha.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jIntFrameTelaLogin = new javax.swing.JInternalFrame();
        btnLogoff = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        btnAlterarSenha = new javax.swing.JButton();
        btnConfirmarSenha = new javax.swing.JButton();
        txtLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        txtConfirmaSenha = new javax.swing.JPasswordField();
        lblLogin = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblConfirmarSenha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mnuBarMenuPrincipal = new javax.swing.JMenuBar();
        mnuGestao = new javax.swing.JMenu();
        mnuUsuarios = new javax.swing.JMenu();
        mnuItemCadastroUsuario = new javax.swing.JMenuItem();
        mnuItemConsultaUsuario = new javax.swing.JMenuItem();
        mnuBeneficios = new javax.swing.JMenu();
        mnuItemCadastroBeneficio = new javax.swing.JMenuItem();
        mnuItemConsultaBeneficio = new javax.swing.JMenuItem();
        mnuBeneficiarios = new javax.swing.JMenu();
        mnuItemCadastroBeneficiario = new javax.swing.JMenuItem();
        mnuItemConsultaBeneficiarios = new javax.swing.JMenuItem();
        mnuPedidoAveriguacao = new javax.swing.JMenu();
        mnuItemCadastroPedido = new javax.swing.JMenuItem();
        mnuItemConsultaPedido = new javax.swing.JMenuItem();
        mnuResultadoAveriguacao = new javax.swing.JMenu();
        mnuItemCadastroResultado = new javax.swing.JMenuItem();
        mnuItemConsultaResultado = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        ItemConsultaBeneficiarios = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuReltaorios = new javax.swing.JMenu();
        mnuAjuda = new javax.swing.JMenu();
        mnuUsuarioAtivo = new javax.swing.JMenu();
        mnuItemAlterarSenha = new javax.swing.JMenuItem();
        mnuItemSair = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Principal");

        jIntFrameTelaLogin.setTitle("Tela de Login");
        jIntFrameTelaLogin.setVisible(true);

        btnLogoff.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnLogoff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabe/apresentacao/icones/user_delete.png"))); // NOI18N
        btnLogoff.setText("Logoff");
        btnLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoffActionPerformed(evt);
            }
        });

        btnLogin.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabe/apresentacao/icones/user.png"))); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnAlterarSenha.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnAlterarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabe/apresentacao/icones/key.png"))); // NOI18N
        btnAlterarSenha.setText("Alterar Senha");
        btnAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarSenhaActionPerformed(evt);
            }
        });

        btnConfirmarSenha.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnConfirmarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabe/apresentacao/icones/arrow_refresh.png"))); // NOI18N
        btnConfirmarSenha.setText("Confirmar Senha");
        btnConfirmarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarSenhaActionPerformed(evt);
            }
        });

        txtLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLogin.setAlignmentX(6.0F);
        txtLogin.setBorder(null);
        txtLogin.setMaximumSize(new java.awt.Dimension(10, 10));

        txtSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSenha.setAlignmentX(6.0F);
        txtSenha.setBorder(null);
        txtSenha.setMaximumSize(new java.awt.Dimension(10, 10));

        txtConfirmaSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtConfirmaSenha.setAlignmentX(6.0F);
        txtConfirmaSenha.setBorder(null);
        txtConfirmaSenha.setMaximumSize(new java.awt.Dimension(10, 10));

        lblLogin.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin.setText("LOGIN:");
        lblLogin.setAlignmentX(6.0F);
        lblLogin.setBorder(null);
        lblLogin.setMaximumSize(new java.awt.Dimension(10, 10));

        lblSenha.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lblSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSenha.setText("SENHA:");
        lblSenha.setAlignmentX(6.0F);
        lblSenha.setBorder(null);
        lblSenha.setMaximumSize(new java.awt.Dimension(10, 10));

        lblConfirmarSenha.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lblConfirmarSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConfirmarSenha.setText("CONFIRMA SENHA:");
        lblConfirmarSenha.setAlignmentX(6.0F);
        lblConfirmarSenha.setBorder(null);
        lblConfirmarSenha.setMaximumSize(new java.awt.Dimension(10, 10));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SAB - SISTEMA DE AVERIGUAÇÃO DE BENEFIÁRIOS");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabe/apresentacao/icones/searcher_1.png"))); // NOI18N

        javax.swing.GroupLayout jIntFrameTelaLoginLayout = new javax.swing.GroupLayout(jIntFrameTelaLogin.getContentPane());
        jIntFrameTelaLogin.getContentPane().setLayout(jIntFrameTelaLoginLayout);
        jIntFrameTelaLoginLayout.setHorizontalGroup(
            jIntFrameTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIntFrameTelaLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jIntFrameTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jIntFrameTelaLoginLayout.createSequentialGroup()
                        .addComponent(btnLogoff, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(btnAlterarSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConfirmarSenha))
                    .addGroup(jIntFrameTelaLoginLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jIntFrameTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jIntFrameTelaLoginLayout.createSequentialGroup()
                                .addComponent(lblConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtConfirmaSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jIntFrameTelaLoginLayout.createSequentialGroup()
                                .addGroup(jIntFrameTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(lblLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jIntFrameTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        jIntFrameTelaLoginLayout.setVerticalGroup(
            jIntFrameTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIntFrameTelaLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jIntFrameTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jIntFrameTelaLoginLayout.createSequentialGroup()
                        .addGroup(jIntFrameTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jIntFrameTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jIntFrameTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(jIntFrameTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogoff, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        mnuBarMenuPrincipal.setPreferredSize(new java.awt.Dimension(360, 35));

        mnuGestao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabe/apresentacao/icones/application_form_add.png"))); // NOI18N
        mnuGestao.setText("Gestão");

        mnuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabe/apresentacao/icones/business133_1.png"))); // NOI18N
        mnuUsuarios.setText("Usuario");

        mnuItemCadastroUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK));
        mnuItemCadastroUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabe/apresentacao/icones/add.png"))); // NOI18N
        mnuItemCadastroUsuario.setText("Cadastro");
        mnuItemCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCadastroUsuarioActionPerformed(evt);
            }
        });
        mnuUsuarios.add(mnuItemCadastroUsuario);

        mnuItemConsultaUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        mnuItemConsultaUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabe/apresentacao/icones/zoom.png"))); // NOI18N
        mnuItemConsultaUsuario.setText("Consulta");
        mnuItemConsultaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemConsultaUsuarioActionPerformed(evt);
            }
        });
        mnuUsuarios.add(mnuItemConsultaUsuario);

        mnuGestao.add(mnuUsuarios);

        mnuBeneficios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabe/apresentacao/icones/credit card3.png"))); // NOI18N
        mnuBeneficios.setText("Beneficio");

        mnuItemCadastroBeneficio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK));
        mnuItemCadastroBeneficio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabe/apresentacao/icones/add.png"))); // NOI18N
        mnuItemCadastroBeneficio.setText("Cadastro");
        mnuItemCadastroBeneficio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCadastroBeneficioActionPerformed(evt);
            }
        });
        mnuBeneficios.add(mnuItemCadastroBeneficio);

        mnuItemConsultaBeneficio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        mnuItemConsultaBeneficio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabe/apresentacao/icones/zoom.png"))); // NOI18N
        mnuItemConsultaBeneficio.setText("Consulta");
        mnuItemConsultaBeneficio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemConsultaBeneficioActionPerformed(evt);
            }
        });
        mnuBeneficios.add(mnuItemConsultaBeneficio);

        mnuGestao.add(mnuBeneficios);

        mnuBeneficiarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabe/apresentacao/icones/family-of-four-in-front-of-their-home(1)_1.png"))); // NOI18N
        mnuBeneficiarios.setText("Beneficiários");

        mnuItemCadastroBeneficiario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_MASK));
        mnuItemCadastroBeneficiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabe/apresentacao/icones/add.png"))); // NOI18N
        mnuItemCadastroBeneficiario.setText("Cadastro");
        mnuItemCadastroBeneficiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCadastroBeneficiarioActionPerformed(evt);
            }
        });
        mnuBeneficiarios.add(mnuItemCadastroBeneficiario);

        mnuItemConsultaBeneficiarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        mnuItemConsultaBeneficiarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabe/apresentacao/icones/zoom.png"))); // NOI18N
        mnuItemConsultaBeneficiarios.setText("Consulta");
        mnuItemConsultaBeneficiarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemConsultaBeneficiariosActionPerformed(evt);
            }
        });
        mnuBeneficiarios.add(mnuItemConsultaBeneficiarios);

        mnuGestao.add(mnuBeneficiarios);

        mnuPedidoAveriguacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabe/apresentacao/icones/searcher(2).png"))); // NOI18N
        mnuPedidoAveriguacao.setText("Pedido de Averiguação");

        mnuItemCadastroPedido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        mnuItemCadastroPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabe/apresentacao/icones/add.png"))); // NOI18N
        mnuItemCadastroPedido.setText("Cadastra");
        mnuItemCadastroPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCadastroPedidoActionPerformed(evt);
            }
        });
        mnuPedidoAveriguacao.add(mnuItemCadastroPedido);

        mnuItemConsultaPedido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        mnuItemConsultaPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabe/apresentacao/icones/zoom.png"))); // NOI18N
        mnuItemConsultaPedido.setText("Consulta");
        mnuItemConsultaPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemConsultaPedidoActionPerformed(evt);
            }
        });
        mnuPedidoAveriguacao.add(mnuItemConsultaPedido);

        mnuGestao.add(mnuPedidoAveriguacao);

        mnuResultadoAveriguacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabe/apresentacao/icones/document9_1.png"))); // NOI18N
        mnuResultadoAveriguacao.setText("Resultado Averiguação");

        mnuItemCadastroResultado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK));
        mnuItemCadastroResultado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabe/apresentacao/icones/add.png"))); // NOI18N
        mnuItemCadastroResultado.setText("Cadastra");
        mnuItemCadastroResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCadastroResultadoActionPerformed(evt);
            }
        });
        mnuResultadoAveriguacao.add(mnuItemCadastroResultado);

        mnuItemConsultaResultado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        mnuItemConsultaResultado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabe/apresentacao/icones/zoom.png"))); // NOI18N
        mnuItemConsultaResultado.setText("Consulta");
        mnuItemConsultaResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemConsultaResultadoActionPerformed(evt);
            }
        });
        mnuResultadoAveriguacao.add(mnuItemConsultaResultado);

        mnuGestao.add(mnuResultadoAveriguacao);

        mnuBarMenuPrincipal.add(mnuGestao);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabe/apresentacao/icones/zoom.png"))); // NOI18N
        jMenu1.setText("Consultas");

        ItemConsultaBeneficiarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        ItemConsultaBeneficiarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabe/apresentacao/icones/family-of-four-in-front-of-their-home(1)_1.png"))); // NOI18N
        ItemConsultaBeneficiarios.setText("Beneficiarios");
        ItemConsultaBeneficiarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemConsultaBeneficiariosActionPerformed(evt);
            }
        });
        jMenu1.add(ItemConsultaBeneficiarios);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabe/apresentacao/icones/newspaper11.png"))); // NOI18N
        jMenuItem3.setText("Averiguações");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator2);

        mnuBarMenuPrincipal.add(jMenu1);

        mnuReltaorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabe/apresentacao/icones/page_white_acrobat.png"))); // NOI18N
        mnuReltaorios.setText("Relatorios");
        mnuReltaorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReltaoriosActionPerformed(evt);
            }
        });
        mnuBarMenuPrincipal.add(mnuReltaorios);

        mnuAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabe/apresentacao/icones/help.png"))); // NOI18N
        mnuAjuda.setText("Ajuda");
        mnuBarMenuPrincipal.add(mnuAjuda);

        mnuUsuarioAtivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabe/apresentacao/icones/user.png"))); // NOI18N

        mnuItemAlterarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabe/apresentacao/icones/key.png"))); // NOI18N
        mnuItemAlterarSenha.setText("Alterar senha");
        mnuItemAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemAlterarSenhaActionPerformed(evt);
            }
        });
        mnuUsuarioAtivo.add(mnuItemAlterarSenha);

        mnuItemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sabe/apresentacao/icones/user_delete.png"))); // NOI18N
        mnuItemSair.setText("Sair");
        mnuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemSairActionPerformed(evt);
            }
        });
        mnuUsuarioAtivo.add(mnuItemSair);

        mnuBarMenuPrincipal.add(mnuUsuarioAtivo);

        setJMenuBar(mnuBarMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jIntFrameTelaLogin)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jIntFrameTelaLogin)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
         try {
            lerDados();
            UsuarioBO usuarioBO = new UsuarioBO();
            usuario = usuarioBO.buscarLoginAndSenha(login, senha);
            exibirMensagemSucesso("Você logou com o usuario: " + usuario.getNome(), "Login usuário");
            this.mnuUsuarioAtivo.setText(usuario.getNome());
            this.mostrarComponentsComUsuario();
            this.carregarUsuarioPermissao();
        } catch(CampoObrigatorioException coe){
            exibirMensagemErro(coe.getMessage(), "Login usuário");
        } catch(ArgumentoInvalidoException aie){
            exibirMensagemErro(aie.getMessage(), "Login usuário");
        } catch (Exception e) {
            exibirMensagemErro("Erro desconhecido. Entre em contato com o adminstrador.", "Login usuário");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarSenhaActionPerformed
        mostrarComponentesAlterarSenha();
    }//GEN-LAST:event_btnAlterarSenhaActionPerformed

    private void btnLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoffActionPerformed
        int resposta;
        String mensagem = "Deseja sair da sua conta?";
        String titulo = "Sair";
        resposta = JOptionPane.showConfirmDialog(null, mensagem, titulo, JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {
            limparCamposTela();
            mostrarComponentsSemUsuario();
        }
    }//GEN-LAST:event_btnLogoffActionPerformed

    private void btnConfirmarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarSenhaActionPerformed
        try{
            int resposta;
            String mensagem = "Confirmar nova senha?";
            String titulo = "Alterar Senha";
            resposta = JOptionPane.showConfirmDialog(null, mensagem, titulo, JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) {
                AlterarSenha();
                UsuarioBO usuarioBO= new UsuarioBO();
                usuarioBO.alterarSenha(usuario);
                exibirMensagemSucesso("Senha cadastrada com sucesso!","Alterar Senha");
                mostrarComponentsComUsuario();
            }
        }catch(SistemaAveriguacaoException sae){
            exibirMensagemErro(sae.getMessage(), "Alterar Senha");
        } catch (SQLException ex) {
            exibirMensagemErro("Erro desconhecido! Contate o administrador do sistema", "Alterar Senha");
        }
    }//GEN-LAST:event_btnConfirmarSenhaActionPerformed

    private void mnuItemCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCadastroUsuarioActionPerformed
        if(cadastroUsuario == null){
            cadastroUsuario = new CadastroUsuarioForm();
        }
        cadastroUsuario.setVisible(true);
        cadastroUsuario.toFront();
    }//GEN-LAST:event_mnuItemCadastroUsuarioActionPerformed

    private void mnuItemConsultaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemConsultaUsuarioActionPerformed
        if(consultaUsuario == null){
            consultaUsuario = new ConsultarUsuarioForm();
        }
        consultaUsuario.toFront();
        consultaUsuario.setVisible(true);
    }//GEN-LAST:event_mnuItemConsultaUsuarioActionPerformed

    private void mnuItemAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemAlterarSenhaActionPerformed
        mostrarComponentesAlterarSenha();
        this.AlterarSenha();
    }//GEN-LAST:event_mnuItemAlterarSenhaActionPerformed

    private void mnuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemSairActionPerformed
        // TODO add your handling code here:
        int resposta;
        String mensagem = "Deseja sair do sistema ?";
        String titulo = "Sair";
        resposta = JOptionPane.showConfirmDialog(null, mensagem, titulo, JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_mnuItemSairActionPerformed

    private void mnuItemCadastroBeneficioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCadastroBeneficioActionPerformed
        if(cadastroBeneficio == null){
            cadastroBeneficio = new CadastroBeneficioForm();
        }
        cadastroBeneficio.setVisible(true);
    }//GEN-LAST:event_mnuItemCadastroBeneficioActionPerformed

    private void mnuItemCadastroResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCadastroResultadoActionPerformed
        if(cadastroResultadoAveriguacao == null){
            cadastroResultadoAveriguacao  = new CadastroResultadoAveriguacaoForm();
        }
        cadastroResultadoAveriguacao .setVisible(true);
    }//GEN-LAST:event_mnuItemCadastroResultadoActionPerformed

    private void mnuItemCadastroPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCadastroPedidoActionPerformed
        if(cadastroPedidoAveriguacao == null){
            cadastroPedidoAveriguacao  = new CadastroPedidoAveriguacaoForm();
        }
        cadastroPedidoAveriguacao.setVisible(true);
    }//GEN-LAST:event_mnuItemCadastroPedidoActionPerformed

    private void mnuItemConsultaPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemConsultaPedidoActionPerformed
        if(consultaPedidoAveriguacao == null){
            consultaPedidoAveriguacao  = new ConsultaPedidoAveriguacaoForm();
        }
        consultaPedidoAveriguacao.setVisible(true);
    }//GEN-LAST:event_mnuItemConsultaPedidoActionPerformed

    private void mnuItemCadastroBeneficiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCadastroBeneficiarioActionPerformed
        if(cadastroBeneficiario == null){
            cadastroBeneficiario  = new CadastroBeneficiarioForm();
        }
        cadastroBeneficiario.setVisible(true);
    }//GEN-LAST:event_mnuItemCadastroBeneficiarioActionPerformed

    private void mnuItemConsultaBeneficiariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemConsultaBeneficiariosActionPerformed
        if(consultaBeneficiario == null){
            consultaBeneficiario  = new ConsultaBeneficiarioForm();
        }
        consultaBeneficiario.setVisible(true);
    }//GEN-LAST:event_mnuItemConsultaBeneficiariosActionPerformed

    private void mnuItemConsultaBeneficioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemConsultaBeneficioActionPerformed
        if(consultaBeneficio == null){
            consultaBeneficio  = new ConsultaBeneficioForm();
        }
        consultaBeneficio.setVisible(true);
    }//GEN-LAST:event_mnuItemConsultaBeneficioActionPerformed

    private void mnuItemConsultaResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemConsultaResultadoActionPerformed
        if(consultaResultadoAveriguacao == null){
            consultaResultadoAveriguacao  = new ConsultaResultadoAveriguacaoForm();
        }
        consultaResultadoAveriguacao.setVisible(true);
    }//GEN-LAST:event_mnuItemConsultaResultadoActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void ItemConsultaBeneficiariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemConsultaBeneficiariosActionPerformed
        if(consultaBeneficiario == null){
            consultaBeneficiario  = new ConsultaBeneficiarioForm();
        }
        consultaBeneficiario.setVisible(true);
    }//GEN-LAST:event_ItemConsultaBeneficiariosActionPerformed

    private void mnuReltaoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReltaoriosActionPerformed
        if(telaRelatorios == null){
            telaRelatorios  = new TelaRelatorios();
        }
        telaRelatorios.setVisible(true);
    }//GEN-LAST:event_mnuReltaoriosActionPerformed
    
    public void exibirMensagemErro(String mensagem, String titulo) {
        JOptionPane.showMessageDialog(this, mensagem, titulo, JOptionPane.ERROR_MESSAGE);
    }

    public void exibirMensagemSucesso(String mensagem, String titulo) {
        JOptionPane.showMessageDialog(this, mensagem, titulo, JOptionPane.INFORMATION_MESSAGE);
    }
    public void lerDados() throws NoSuchAlgorithmException, UnsupportedEncodingException{
        String login = txtLogin.getText().trim();
        String senha = txtSenha.getText().trim();
        
        String mensagem = "";
        
        if(login.isEmpty()){
            mensagem = "Campo login é obrigatorio";
        }
        
        if(senha.isEmpty()){
            mensagem = "Campo senha é obrigatório";
        }
        if(mensagem == "" || mensagem == null){
            this.login = login;
            this.senha = Criptografia.exemploMD5(senha);
        }else{
            throw new CampoObrigatorioException(mensagem);
        }
    }
    public void AlterarSenha(){
        String novaSenha = txtSenha.getText().trim();
        String confirmaNovaSenha = txtConfirmaSenha.getText().trim();
        if(senha == "" && confirmaNovaSenha == ""){
            throw new CampoObrigatorioException("Prencha os campos vazios!");
        } 
        if(novaSenha.equals(confirmaNovaSenha)){
            this.usuario.setSenha(novaSenha);
        }else{
            throw new CampoObrigatorioException("Senhas nao conferem!");
        }
    }
    public void limparCamposTela(){
        this.txtLogin.setText("");
        this.txtSenha.setText("");
        this.txtConfirmaSenha.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {               
                new TelaPrincipalForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemConsultaBeneficiarios;
    private javax.swing.JButton btnAlterarSenha;
    private javax.swing.JButton btnConfirmarSenha;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogoff;
    private javax.swing.JInternalFrame jIntFrameTelaLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lblConfirmarSenha;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JMenu mnuAjuda;
    private javax.swing.JMenuBar mnuBarMenuPrincipal;
    private javax.swing.JMenu mnuBeneficiarios;
    private javax.swing.JMenu mnuBeneficios;
    private javax.swing.JMenu mnuGestao;
    private javax.swing.JMenuItem mnuItemAlterarSenha;
    private javax.swing.JMenuItem mnuItemCadastroBeneficiario;
    private javax.swing.JMenuItem mnuItemCadastroBeneficio;
    private javax.swing.JMenuItem mnuItemCadastroPedido;
    private javax.swing.JMenuItem mnuItemCadastroResultado;
    private javax.swing.JMenuItem mnuItemCadastroUsuario;
    private javax.swing.JMenuItem mnuItemConsultaBeneficiarios;
    private javax.swing.JMenuItem mnuItemConsultaBeneficio;
    private javax.swing.JMenuItem mnuItemConsultaPedido;
    private javax.swing.JMenuItem mnuItemConsultaResultado;
    private javax.swing.JMenuItem mnuItemConsultaUsuario;
    private javax.swing.JMenuItem mnuItemSair;
    private javax.swing.JMenu mnuPedidoAveriguacao;
    private javax.swing.JMenu mnuReltaorios;
    private javax.swing.JMenu mnuResultadoAveriguacao;
    private javax.swing.JMenu mnuUsuarioAtivo;
    private javax.swing.JMenu mnuUsuarios;
    private javax.swing.JPasswordField txtConfirmaSenha;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
