/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sabe.apresentacao;

import br.com.sabe.entidade.LocalidadesVisitadas;
import br.com.sabe.entidade.PedidoAveriguacao;
import br.com.sabe.entidade.SituacaoBeneficiarios;
import br.com.sabe.excecao.CampoObrigatorioException;
import br.com.sabe.excecao.SistemaAveriguacaoException;
import br.com.sabe.negocio.PedidoAveriguacaoBO;
import br.com.sabe.negocio.ResultadoAveriguacaoBO;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author walisson
 */
public class TelaRelatorios extends javax.swing.JFrame {
    List<SituacaoBeneficiarios> listaSituacaoBeneficiarios;
    List<LocalidadesVisitadas> listaLocalidadesVisitadas;
    Date dataInicio;
    Date dataTermino;
    /**
     * Creates new form RelatorioLocalidadesVisitadas
     */
    public TelaRelatorios() {
        initComponents();
    }
    private void recuperarCamposTela() throws ParseException {
        if(txtDataInicio != null && txtDataTermino != null){
            SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
            this.dataInicio = formatador.parse(txtDataInicio.getText().trim());
            this.dataTermino = formatador.parse(txtDataTermino.getText().trim());
        }else{
            throw new CampoObrigatorioException();
        }          
    }
    public void gerarRelatorioLocalidadesVisitadas() throws SQLException{
        try{
            String arquivoRelatorio = System.getProperty("user.dir");
            arquivoRelatorio += "/relatorios/LocalidadesVisitadas.jasper";
            
            Map<String, Object> parametros = new HashMap<String, Object>();
            
            JRBeanCollectionDataSource fonteDados = new JRBeanCollectionDataSource(this.listaLocalidadesVisitadas);
            
            JasperPrint relatorioGerado = JasperFillManager.fillReport(arquivoRelatorio, parametros, fonteDados);
                            
            JasperViewer telaExibicaoRelatorio = new JasperViewer(relatorioGerado, false);
            telaExibicaoRelatorio.setTitle("Relatório de Localidades Visitadas");
            telaExibicaoRelatorio.setVisible(true);                        
        }catch(JRException e){
            JOptionPane.showMessageDialog(this, 
                    "Erro ao exibir relatório.",
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }      
    }
    public void gerarRelatorioSituacaoBeneficiarios() throws SQLException{
        try{
            String arquivoRelatorio = System.getProperty("user.dir");
            arquivoRelatorio += "/relatorios/SituacaoBeneficiarios.jasper";
            
            Map<String, Object> parametros = new HashMap<String, Object>();
            
            JRBeanCollectionDataSource fonteDados = new JRBeanCollectionDataSource(this.listaSituacaoBeneficiarios);
            
            JasperPrint relatorioGerado = JasperFillManager.fillReport(arquivoRelatorio, parametros, fonteDados);
                            
            JasperViewer telaExibicaoRelatorio = new JasperViewer(relatorioGerado, false);
            telaExibicaoRelatorio.setTitle("Relatório de Sistuação de Beneficiários");
            telaExibicaoRelatorio.setVisible(true);                        
        }catch(JRException e){
            JOptionPane.showMessageDialog(this, 
                    "Erro ao exibir relatório.",
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTipoRelatorio = new javax.swing.ButtonGroup();
        pnlFiltroRelatorio = new javax.swing.JPanel();
        btnGerarRelatorio = new javax.swing.JButton();
        rdoLocalidadesVisitadas = new javax.swing.JRadioButton();
        rdoSistuacaoBeneficiarios = new javax.swing.JRadioButton();
        lblTipoRelatorio = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtDataInicio = new javax.swing.JFormattedTextField();
        lblDataInicio = new javax.swing.JLabel();
        txtDataTermino = new javax.swing.JFormattedTextField();
        lblDataTermino = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        pnlFiltroRelatorio.setBorder(javax.swing.BorderFactory.createTitledBorder("Relatórios Gerenciais"));

        btnGerarRelatorio.setText("Gerar Relatório");
        btnGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarRelatorioActionPerformed(evt);
            }
        });

        btnTipoRelatorio.add(rdoLocalidadesVisitadas);
        rdoLocalidadesVisitadas.setText("Localidades Visitadas");

        btnTipoRelatorio.add(rdoSistuacaoBeneficiarios);
        rdoSistuacaoBeneficiarios.setText("Situação de Beneficiarios");

        lblTipoRelatorio.setText("Tipo do Relatório:");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Período"));

        txtDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        lblDataInicio.setText("Data Inicio:");

        txtDataTermino.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        lblDataTermino.setText("Data termino:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDataTermino)
                        .addGap(18, 18, 18)
                        .addComponent(txtDataTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDataInicio)
                        .addGap(38, 38, 38)
                        .addComponent(txtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataInicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataTermino)
                    .addComponent(txtDataTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout pnlFiltroRelatorioLayout = new javax.swing.GroupLayout(pnlFiltroRelatorio);
        pnlFiltroRelatorio.setLayout(pnlFiltroRelatorioLayout);
        pnlFiltroRelatorioLayout.setHorizontalGroup(
            pnlFiltroRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltroRelatorioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFiltroRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFiltroRelatorioLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnlFiltroRelatorioLayout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGerarRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFiltroRelatorioLayout.createSequentialGroup()
                        .addComponent(lblTipoRelatorio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoLocalidadesVisitadas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoSistuacaoBeneficiarios)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlFiltroRelatorioLayout.setVerticalGroup(
            pnlFiltroRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltroRelatorioLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlFiltroRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoLocalidadesVisitadas)
                    .addComponent(lblTipoRelatorio)
                    .addComponent(rdoSistuacaoBeneficiarios))
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFiltroRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGerarRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFiltroRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFiltroRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarRelatorioActionPerformed
        try{
            if(rdoLocalidadesVisitadas.isSelected()){
                ResultadoAveriguacaoBO resultadoAveriguacaoBO = new ResultadoAveriguacaoBO();
                this.recuperarCamposTela();
                this.listaLocalidadesVisitadas = resultadoAveriguacaoBO.buscarLocalidadesVisitadas(this.dataInicio, this.dataTermino);
                this.gerarRelatorioLocalidadesVisitadas();
            }else if(rdoSistuacaoBeneficiarios.isSelected()){     
                PedidoAveriguacaoBO pedidoAveriguacaoBO= new PedidoAveriguacaoBO();
                this.recuperarCamposTela();
                this.listaSituacaoBeneficiarios = pedidoAveriguacaoBO.buscarSituaçõesBeneficiarios(this.dataInicio, this.dataTermino);                                        
                this.gerarRelatorioLocalidadesVisitadas();
            }else{
                throw new CampoObrigatorioException("Escolha um tipo de Relatorio!");
            }
        }catch(SistemaAveriguacaoException sae){
            JOptionPane.showMessageDialog(this, 
                "Erro ao exibir relatório.",
                sae.getMessage(), JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(TelaRelatorios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException px) {
            Logger.getLogger(TelaRelatorios.class.getName()).log(Level.SEVERE, null, px);
        }        
    }//GEN-LAST:event_btnGerarRelatorioActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRelatorios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGerarRelatorio;
    private javax.swing.ButtonGroup btnTipoRelatorio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDataInicio;
    private javax.swing.JLabel lblDataTermino;
    private javax.swing.JLabel lblTipoRelatorio;
    private javax.swing.JPanel pnlFiltroRelatorio;
    private javax.swing.JRadioButton rdoLocalidadesVisitadas;
    private javax.swing.JRadioButton rdoSistuacaoBeneficiarios;
    private javax.swing.JFormattedTextField txtDataInicio;
    private javax.swing.JFormattedTextField txtDataTermino;
    // End of variables declaration//GEN-END:variables

   
}
