CREATE TABLE USUARIO(
ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
NOME VARCHAR(50) NOT NULL,
LOGIN VARCHAR(8) NOT NULL UNIQUE,
SENHA VARCHAR(32) NOT NULL,
CARGO CHAR(2) NOT NULL);
===================================================================
CREATE TABLE BENEFICIO(
ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
NOME VARCHAR(30) NOT NULL UNIQUE,
TIPO VARCHAR(30) NOT NULL,
VALOR DOUBLE NOT NULL
);
====================================================================
CREATE TABLE BENEFICIARIO(
ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
NIS CHAR(11) NOT NULL UNIQUE,
NOME VARCHAR(50) NOT NULL,
RUA VARCHAR(50) NOT NULL,
NUMERO INTEGER,
BAIRRO VARCHAR(60),
ZONA CHAR(1) NOT NULL,
LOCALIDADE VARCHAR(50),
QTDE_MEMBROS_DA_FAMILIA INTEGER NOT NULL,
RENDA_FAMILIAR DOUBLE NOT NULL,
RENDA_PER_CAPTA DOUBLE NOT NULL,
ID_BENEFICIO INTEGER REFERENCES BENEFICIO(ID));
====================================================================
INSERT INTO "PUBLIC"."BENEFICIARIO"
( "NIS", "NOME", "RUA", "NUMERO", "BAIRRO", "ZONA","LOCALIDADE", "QTDE_MEMBROS_DA_FAMILIA", "RENDA_FAMILIAR", 
"RENDA_PER_CAPTA" )VALUES ( '11111111112','WEMERSON','JOSE AUGUSTO','790','vv','U','Centro','3','788.00','222.00')

CONSULTAS
SELECT BE.NOME AS BENEFICIO, BA.NOME, BA.NIS FROM BENEFICIO BE LEFT JOIN BENEFICIO_BENEFICIARIO BE_BA ON 
BE.ID=BE_BA.ID_BENEFICIO LEFT JOIN BENEFICIARIO BA ON BE_BA.ID_BENEFICIARIO=BA.ID;
====================================================================

CREATE TABLE BENEFICIO_BENEFICIARIO(
ID_BENEFICIO INTEGER NOT NULL, 
ID_BENEFICIARIO INTEGER NOT NULL, 
PRIMARY KEY(ID_BENEFICIO, ID_BENEFICIARIO),
FOREIGN KEY(ID_BENEFICIO) REFERENCES BENEFICIO(ID),
FOREIGN KEY(ID_BENEFICIARIO) REFERENCES BENEFICIARIO(ID));
=====================================================================

CREATE TABLE PEDIDO(
ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
SITUACAO VARCHAR(200) NOT NULL,
ID_BENEFICIARIO INTEGER NOT NULL,
FOREIGN KEY(ID_BENEFICIARIO) REFERENCES BENEFICIARIO(ID));

INSERT INTO "PUBLIC"."PEDIDO"
( "SITUACAO", "ID_BENEFICIARIO" )
VALUES ('VERIFICAR SE DANILO RESIDE NA CASA', '2' );
======================================================================
CREATE TABLE RESULTADO(
ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
RESULTADO VARCHAR(200),
DECISAO VARCHAR(30),
ID_PEDIDO INTEGER NOT NULL REFERENCES PEDIDO(ID));

INSERT INTO "PUBLIC"."RESULTADO"
("RESULTADO", "DECISAO" )
VALUES ('DANILO MORA NA CASA', 'RECADASTRAR');
=======================================================================
CREATE TABLE AVERIGUACAO(
ID_PEDIDO INTEGER NOT NULL,
ID_RESULTADO INTEGER NOT NULL,
PRIMARY KEY(ID_PEDIDO, ID_RESULTADO),
FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDO(ID),
FOREIGN KEY(ID_RESULTADO) REFERENCES RESULTADO(ID));
================================

CREATE TABLE RESULT(
ID INTEGER NOT NULL IDENTITY,
ID_PEDIDO INTEGER NOT NULL,
RESULTADO VARCHAR(200),
DECISAO VARCHAR(30),
CONSTRAINT PK_PEDIDO PRIMARY KEY(ID, ID_PEDIDO),
CONSTRAINT FK_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID));



SELECT B.NOME AS BENEFICIARIO, P.SITUACAO AS SITUACAO, R.RESULTADO AS RESULTADO, R.DECISAO DECISAO
FROM BENEFICIARIO B INNER JOIN PEDIDO P ON B.ID = P.ID_BENEFICIARIO JOIN AVERIGUACAO A ON P.ID=A.ID_PEDIDO JOIN RESULTADO R ON A.ID_RESULTADO=R.ID

